app = "frontdesk-ai_-poc"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[services.concurrency]
  hard_limit = 1
  soft_limit = 1
  type = "connections"
